### ISSUE TITLE
Cannot add new language for directions

### ISSUE THREAD

**Issue by nexces** [GIScience/openrouteservice#607]
I’ve followed directions in https://github.com/GIScience/openrouteservice/wiki/Contributing-Translations and I see new language available in “/status” endpoint. However when I’m trying to use new language I’m getting “Parameter ‘language’ has incorrect value or format.”

#### Response from `/ors/status/`
```
{
    "engine": {
        "version": "5.0.2",
        "build_date": "2019-11-06T14:15:06Z"
    },
    "services": [
        "routing",
        "geocoding",
        "isochrones",
        "matrix",
        "mapmatching"
    ],
    "languages": [
        "de-de",
        "en",
        "en-us",
        "es-es",
        "fr-fr",
        "gr-gr",
        "hu-hu",
        "it-it",
        "ne-np",
        "nl-nl",
        "pl",
        "pl-pl",
        "pt-pt",
        "ru-ru",
        "zh-cn"
    ],
    "profiles": {
        "profile 1": {
            "profiles": "driving-car",
            "creation_date": "",
            "storages": {
                "WayCategory": {},
                "HeavyVehicle": {},
                "WaySurfaceType": {},
                "RoadAccessRestrictions": {
                    "use_for_warnings": "true"
                }
            },
            "limits": {
                "maximum_distance": 1000000,
                "maximum_distance_dynamic_weights": 100000,
                "maximum_distance_avoid_areas": 100000,
                "maximum_waypoints": 50
            }
        },
        "profile 2": {
            "profiles": "driving-hgv",
            "creation_date": "",
            "storages": {
                "WayCategory": {},
                "HeavyVehicle": {
                    "restrictions": "true"
                },
                "WaySurfaceType": {}
            },
            "limits": {
                "maximum_distance": 1000000,
                "maximum_distance_dynamic_weights": 100000,
                "maximum_distance_avoid_areas": 100000,
                "maximum_waypoints": 50
            }
        }
    }
}
```
---

#### Request sent to `/ors/v2/directions/driving-hgv`
```
{
	"coordinates": [
		[20.412565, 53.769033],
		[20.504522, 53.781961]
	],
        "geometry": false,
	"language": "pl"
}
```

---
#### Response for `"language": "pl"`
```
{
    "error": {
        "code": 2003,
        "message": "Parameter 'language' has incorrect value or format."
    },
    "info": {
        "engine": {
            "version": "5.0.2",
            "build_date": "2019-11-06T14:15:06Z"
        },
        "timestamp": 1573210689808
    }
}
```

---
#### Response for `"language": "en"`
```
{
    "routes": [
        {
            "summary": {
                "distance": 7319.4,
                "duration": 606.3
            },
            "segments": [
                {
                    "distance": 7319.4,
                    "duration": 606.3,
                    "steps": [
                        {
                            "distance": 288.1,
                            "duration": 69.1,
                            "type": 11,
                            "instruction": "Head east on Słonecznikowa",
                            "name": "Słonecznikowa",
                            "way_points": [
                                0,
                                6
                            ]
                        },
                        {
                            "distance": 52.0,
                            "duration": 12.5,
                            "type": 0,
                            "instruction": "Turn left onto Zbożowa",
                            "name": "Zbożowa",
                            "way_points": [
                                6,
                                7
                            ]
                        },
                        {
                            "distance": 45.6,
                            "duration": 10.9,
                            "type": 1,
                            "instruction": "Turn right onto Sielska",
                            "name": "Sielska",
                            "way_points": [
                                7,
                                8
                            ]
                        },
                        {
                            "distance": 42.1,
                            "duration": 10.1,
                            "type": 2,
                            "instruction": "Turn sharp left onto Sielska",
                            "name": "Sielska",
                            "way_points": [
                                8,
                                10
                            ]
                        },
                        {
                            "distance": 2644.3,
                            "duration": 207.8,
                            "type": 1,
                            "instruction": "Turn right onto Sielska",
                            "name": "Sielska",
                            "way_points": [
                                10,
                                75
                            ]
                        },
                        {
                            "distance": 725.3,
                            "duration": 48.1,
                            "type": 0,
                            "instruction": "Turn left onto Aleja Roberta Schumana",
                            "name": "Aleja Roberta Schumana",
                            "way_points": [
                                75,
                                91
                            ]
                        },
                        {
                            "distance": 1136.7,
                            "duration": 78.7,
                            "type": 7,
                            "instruction": "Enter the roundabout and take the 2nd exit onto Artyleryjska",
                            "name": "Artyleryjska",
                            "exit_number": 2,
                            "way_points": [
                                91,
                                118
                            ]
                        },
                        {
                            "distance": 983.3,
                            "duration": 70.8,
                            "type": 1,
                            "instruction": "Turn right onto Partyzantów",
                            "name": "Partyzantów",
                            "way_points": [
                                118,
                                151
                            ]
                        },
                        {
                            "distance": 594.3,
                            "duration": 36.6,
                            "type": 7,
                            "instruction": "Enter the roundabout and take the 2nd exit onto Wojciecha Kętrzyńskiego, 51",
                            "name": "Wojciecha Kętrzyńskiego, 51",
                            "exit_number": 2,
                            "way_points": [
                                151,
                                179
                            ]
                        },
                        {
                            "distance": 508.2,
                            "duration": 31.6,
                            "type": 7,
                            "instruction": "Enter the roundabout and take the 2nd exit onto Towarowa, 51",
                            "name": "Towarowa, 51",
                            "exit_number": 2,
                            "way_points": [
                                179,
                                194
                            ]
                        },
                        {
                            "distance": 228.5,
                            "duration": 17.3,
                            "type": 6,
                            "instruction": "Continue straight onto Towarowa, 51",
                            "name": "Towarowa, 51",
                            "way_points": [
                                194,
                                201
                            ]
                        },
                        {
                            "distance": 10.0,
                            "duration": 1.8,
                            "type": 1,
                            "instruction": "Turn right",
                            "name": "-",
                            "way_points": [
                                201,
                                203
                            ]
                        },
                        {
                            "distance": 38.5,
                            "duration": 6.9,
                            "type": 13,
                            "instruction": "Keep right",
                            "name": "-",
                            "way_points": [
                                203,
                                205
                            ]
                        },
                        {
                            "distance": 22.5,
                            "duration": 4.0,
                            "type": 1,
                            "instruction": "Turn right",
                            "name": "-",
                            "way_points": [
                                205,
                                207
                            ]
                        },
                        {
                            "distance": 0.0,
                            "duration": 0.0,
                            "type": 10,
                            "instruction": "Arrive at your destination, on the right",
                            "name": "-",
                            "way_points": [
                                207,
                                207
                            ]
                        }
                    ]
                }
            ],
            "bbox": [
                20.413,
                53.768166,
                20.507451,
                53.783617
            ]
        }
    ],
    "bbox": [
        20.413,
        53.768166,
        20.507451,
        53.783617
    ],
    "metadata": {
        "attribution": "openrouteservice.org, OpenStreetMap contributors",
        "service": "routing",
        "timestamp": 1573210979383,
        "query": {
            "coordinates": [
                [
                    20.412565,
                    53.769033
                ],
                [
                    20.504522,
                    53.781961
                ]
            ],
            "profile": "driving-hgv",
            "format": "json",
            "language": "en"
        },
        "engine": {
            "version": "5.0.2",
            "build_date": "2019-11-06T14:15:06Z"
        }
    }
}
```

**Comment by nilsnolde** [comment]
It might easiest if you issue a PR (against development), so we can assess the whole situation.

https://github.com/GIScience/openrouteservice/blob/master/CONTRIBUTE.md#pull-requests

**Comment by rabidllama** [comment]
Hi @nexces ,
the problem is that the documentation needs updating a little to add an extra place that needs a value adding in the java code. Since the update to the new v2 API, the code uses Spring Framework and so the values being passed in also need to be declared in the code. If you add a `PL("pl"),` to the `openrouteservice/src/main/java/heigit/ors/api/requests/common/APIEnums.java` file in the `public enum Languages` section, it should then work. Basically, what you would want is:
```java
    public enum Languages {
        DE("de"),
        EN("en"),
        EN_US("en-us"),
        ES("es"),
        FR("fr"),
        GR("gr"),
        HU("hu"),
        IT("it"),
        NE("ne"),
        NL("nl"),
        PL("pl"),
        PT("pt"),
        RU("ru"),
        ZH_CN("zh-cn");
```

It's slightly more complex since the update, but it makes things overall a lot easier in the code.

**Comment by nexces** [comment]
Thanks @rabidllama, now it works.
I'm going to leave this issue open so it will remind about documentation update ;)
When I'll finish fiddling with translation I'll do a pull request with translation.

**Comment by rabidllama** [comment]
I've updated the docs now

**Comment by Michalf87** [comment]
Hi, I've the same problem. I added translation as it is described in wiki and above, after all i run `docker-compose up --build --force-recreate -d ` but i can't see any changes. My language is still missing.

**Comment by rabidllama** [comment]
Which translation? if you added it locally then you need to make sure you are on the correct branch when you run the docker commands

**Comment by koebi** [comment]
Docs are updated and adding a language shouldn't be an issue anymore - given #901, we'll run into any coming up anyways.
