### ISSUE TITLE
[3099] Unable to build an isochrone map.

### ISSUE THREAD

**Issue by krrhodes** [GIScience/openrouteservice#961]
#### Here's what I did

I am trying to generate several isochrones with ORS. 
`body = {"locations":[[36.110422, -79.895855]],"range":[300,200]}
response = requests.post('http://localhost:8080/ors/v2/isochrones/driving-car', json=body, headers={'Authorization':APIKEY_ORS}) 
print(response.status_code, response.reason)
print(response.text)`

One location is at 36.110422, -79.895855, even when creating a request for just these coordinates I still receive error 3099. After viewing this issue https://github.com/GIScience/openrouteservice/issues/202, I also tried reversing the coordinates, but I received the same error. Using the webapp I am able to create an isochrone here https://classic-maps.openrouteservice.org/reach?n1=36.103176&n2=-79.918645&n3=10&a=36.110422,-79.895855&b=0&i=0&j1=30&j2=15&k1=en-US&k2=mi. And using the coordinates from the documented api example I am able to create an isochrone using my instance of the backend.
---
#### Here's what I got

500 
{"error":{"code":3099,"message":"Unable to build an isochrone map."},"info":{"engine":{"version":"6.5.0","build_date":"2021-05-27T22:46:39Z"},"timestamp":1622157201268}}

**Comment by aoles** [comment]
@HendrikLeuschner maybe related to https://github.com/GIScience/openrouteservice/pull/957?

**Comment by HendrikLeuschner** [comment]
Which version of the code are you using? Could you rerun with the current master branch? It has a fix that is potentially relevant, but it is not yet in a release.

**Comment by nilsnolde** [comment]
unless you're on an antarctic expedition, small hint: `[36.110422, -79.895855]` ;)

**Comment by nilsnolde** [comment]
and don't worry, that happens to _everyone_. lat/lon vs lon/lat is one of the most controversial geo things it seems

**Comment by krrhodes** [comment]
> unless you're on an antarctic expedition, small hint: `[36.110422, -79.895855]` ;)

I have tried using both orders of lat/long and long/lat and both produce the same error unfortunately.

**Comment by krrhodes** [comment]
@HendrikLeuschner I have been using the master branch, I will reclone and see if anything changes

**Comment by krrhodes** [comment]
Update: after recloning the repo's current master branch I still face the same issue

**Comment by koebi** [comment]
Hey,

I tried reproducing this, here's what I came up with:
This is the request as posted above. ORS uses [lon, lat], so this point is somewhere in the middle of antarctica - as expected, no isochrone map can be built, though I agree that the error message could be better.
![Screenshot_2021-06-02 investigate 961 - isochrone map - Jupyter Notebook(2)](https://user-images.githubusercontent.com/4692974/120515883-11d8ce80-c3cf-11eb-96f4-81c57d8de6c4.png)

This is the request with coordinates reversed. This is somewhere in the US, so this yields a valid isochrone.
![Screenshot_2021-06-02 investigate 961 - isochrone map - Jupyter Notebook(1)](https://user-images.githubusercontent.com/4692974/120515898-156c5580-c3cf-11eb-996d-eca3a2b4a299.png)

Note, that this is requesting from the public ors-instance, so results from your machine may vary. In that case, please let us know :)

**Comment by krrhodes** [comment]
@koebi 
![image](https://user-images.githubusercontent.com/48464356/121216505-f0ecff00-c84e-11eb-8c9c-98d5c3faea82.png) It still seems to not be working for me, this is on my own instance of ORS. Is there a branch different from master that I should try? The only change in my app.config is the maximum number of locations allowed.

Edit: still does not work with default max locations.

**Comment by krrhodes** [comment]
Update: It seems to work using the public instance of ORS, however for my purpose I need to eventually plot several isochrones on one map so I must use my own instance. It seems to be failing when I try this (both with the master and release 6.5 branches). 
![image](https://user-images.githubusercontent.com/48464356/121220216-6ad2b780-c852-11eb-83a1-a5a3b24dccf5.png) There doesn't seem to be anything interesting in the logs but I may be missing something

**Comment by HendrikLeuschner** [comment]
Which pbf are you using to build this?

**Comment by krrhodes** [comment]
@HendrikLeuschner I am using one of North Carolina from this source https://download.geofabrik.de/north-america/us/north-carolina.html

**Comment by koebi** [comment]
Two things that strikes me as odd are the number of edges (~20k) and nodes (~15k) as well as the time it took to build (~78s).
A `.pbf`-file for North Carolina should have a few million nodes and edges, and take a lot longer to build.

Could you share your `app.config` as well as the full log output?
Are you building via docker, `mvn` from cli or some IDE?

**Comment by koebi** [comment]
In fact, the numbers of edges and nodes are exactly the same as the ones that the included `heidelberg.osm`-file yields:
```
10 Jun 13:43:33 INFO [routing.RoutingProfileManager] - ====> Initializing profiles from '../openrouteservice/src/main/files/heidelberg.osm.gz' (2 threads) ...
10 Jun 13:43:33 INFO [routing.RoutingProfileManager] -                               
10 Jun 13:43:33 INFO [routing.RoutingProfileManager] -                
10 Jun 13:43:33 INFO [routing.RoutingProfile] - [1] Profiles: 'driving-car', location: 'graphs/hd/car'.
10 Jun 13:43:43 INFO [core.PrepareCore] - 0, updates:0, nodes: 12 679, shortcuts:0, dijkstras:39 572, t(dijk):0.1, t(period):0.0, t(lazy):0.0, t(neighbor):0.0, meanDegree:1, algo:0MB, totalMB:521, usedMB:245
…
10 Jun 13:43:49 INFO [core.PrepareCore] - took:3, new shortcuts: 11 540, prepare|shortest|car-ors, dijkstras:464038, t(dijk):2.85, t(period):1.93, t(lazy):0.03, t(neighbor):0.92, meanDegree:5, initSize:15462, periodic:10, lazy:10, neighbor:90, totalMB:521, usedMB:179
10 Jun 13:43:51 INFO [routing.RoutingProfile] - [1] FlagEncoders: 1, bits used [UNKNOWN]/64.
10 Jun 13:43:51 INFO [routing.RoutingProfile] - [1] Capacity: [UNKNOWN]. (edges - 20863, nodes - 15462)
10 Jun 13:43:51 INFO [routing.RoutingProfile] - [1] Total time: 18.531s.
10 Jun 13:43:51 INFO [routing.RoutingProfile] - [1] Finished at: 2021-06-10 13:43:51.

**Comment by koebi** [comment]
This is the request running against my local instance that just finished building NC (after ~18 mins):
![Screenshot_2021-06-10 investigate 961 - isochrone map - Jupyter Notebook](https://user-images.githubusercontent.com/4692974/121522454-68f52980-c9f5-11eb-9085-414e52fde5f1.png)

That seems to work like it should, compared to the public api :)

**Comment by koebi** [comment]
Especially when using docker, it can definitely be a bit tricky to see what data is actually being used.
If you want to make sure that the file mentioned in the logs
```
INFO [routing.RoutingProfileManager] - ====> Initializing profiles from '../openrouteservice/src/main/files/heidelberg.osm.gz' 
```
is actually used, I think the best way is to remove your `graphs`-folder (or whatever docker is configured to use) beforehand.

I think this should resolve the issue, feel free to reopen and comment if there are more problems :)

**Comment by kleenkanteen** [comment]
Issue still happens on a macbook, qgis version 3.34. Possibly happening due to a CRS issue though because for some reason the new layer consisting of points is in the middle of the ocean. No idea why it would happen though as the CRS of the point layer and project layer is EPSG:4326. Worked on another computer (windows) with these settings.

Happened on the older version from 3 months back as well. Tested on both version today. Am hitting the public API. I don't have logs on me as it is happening to a friend.

edit: It was a projection issue. I changed the CRS to match the CRS of data point layer and it finally worked.

**Comment by koebi** [comment]
Hey,

this issue is about isochrones not being available due to:
* coordinates in `[lat, lon]`-format, as opposed to the expected `[lon, lat]`-format
* the wrong pbf file being used for building graphs on a self-hosted instance

To me, it is unclear what you mean by
> Issue still happens […]

especially since you're talking about 
> […] hitting the public API. […]

and this is about a self-hosted instance.

Feel free to refer to the [ask-forum](https://ask.openrouteservice.org/) with a bit more information.

**Comment by aoles** [comment]
Might be related to https://github.com/GIScience/openrouteservice/issues/1573.
